# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f7aa43ffdb091cc9aa7c4489869c498d65ce547c1cc0e9c67f4b9a1141a7a6d0e8c27f8a5c0426db7fd2b2a6dc971c6df6a16ef6350ceb439d6ae2f20b2eaa12

test:
  secret_key_base: da691d06430cf0252739c5f1a9cd26afd2c7e9b69d9ca1a5a0fe9ff1671a7418a131eb8f284670d609c127cc84eb334046a19d2857a98bdd693e5bd276b696e6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
